# @courseId=2dface0f-7780-43b8-90c4-318dfe73da20
# @quizId=b84597ca-8086-4e5c-98f4-05191be6f148
# @questionId=f2e33b08-1825-4c45-9675-cf0da5630a82
# @userId=93bbc8f1-37b2-40a6-a92c-5723dacff1e5

# @TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDViZWE2Yi1jNjY5LTQzZTgtYmViYi00NTA5NTA0MTMzMTMiLCJlbWFpbCI6ImtpbXV0YWlicmlhbjkyMkBnbWFpbC5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTcyOTQxMCwiZXhwIjoxNzUxODE1ODEwfQ.Mjjfece2u6TiF5R0TnlRPjL5997dHlHFoLJZw3GbtNc
# // 2. Get all quizzes for a course
# GET http://localhost:3000/quizzes/course/{{courseId}}


# ###
# POST http://localhost:3000/quizzes
# Content-Type: application/json
# Authorization: Bearer{{}}

# {
#   "title": "Sample Quiz",
#   "courseId": "{{courseId}}",
#   "timeLimit": 30
# }
# // Copy the returned quizId and set it as @quizId for the next steps

# // 4. Update a quiz
# ###
# PUT http://localhost:3000/quizzes/{{quizId}}
# Content-Type: application/json

# {
#   "title": "Updated Quiz Title"
# }

# // 5. Get all questions for a quiz
# ###
# GET http://localhost:3000/quizzes/{{quizId}}/questions

# // 6. Create a question for the quiz
# ###
# POST http://localhost:3000/quizzes/questions
# Content-Type: application/json

# {
#   "question": "What is TypeScript?",
#   "type": "MCQ",
#   "quizId": "{{quizId}}",
#   "options": [
#     { "value": "A language", "isCorrect": true },
#     { "value": "A database", "isCorrect": false },
#     { "value": "A framework", "isCorrect": false }
#   ],
#   "answer": "A language"
# }


# //7. Update a question
# ###
# PUT http://localhost:3000/quizzes/questions/{{questionId}}
# Content-Type: application/json

# {
#   "question": "Updated Question Text"
# }

# // 8. Delete a question
# ###
# DELETE http://localhost:3000/quizzes/questions/{{questionId}}

# // 9. Delete a quiz
# ###
# DELETE http://localhost:3000/quizzes/{{quizId}}

# // 10. Get quiz attempts by user
# ###
# GET http://localhost:3000/quizzes/attempts/user/{{userId}}

# // 11. Create a quiz attempt
# ###
# POST http://localhost:3000/quizzes/attempts
# Content-Type: application/json
# Authorization: {{TOKEN}}

# {
#   "userId": "{{userId}}",
#   "quizId": "{{quizId}}",
#   "answers": [
#     { "questionId": "{{questionId}}", "answer": "A database" }
#   ]
# }

