-- AlterTable
ALTER TABLE "Lesson" ALTER COLUMN "updatedAt" DROP DEFAULT;
   ALTER TABLE "Lesson" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT NOW();
   ALTER TABLE "Lesson" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT NOW();